создал метод для получения книг
neonoir8/book pull request #1
Opened 2023-01-12 12:36 UTC by neonoir8

2023-01-12 19:34 UTC, niyazkadirov commented on src/main/java/com/example/petproject/controllers/BookController.java
> +    public List<Book> getBook() {
getBooks()

2023-01-12 19:35 UTC, niyazkadirov commented on src/main/java/com/example/petproject/services/BookService.java
> +    public List<Book> findAll() {
getBooks

2023-01-12 19:36 UTC, niyazkadirov commented on src/main/java/com/example/petproject/services/BookService.java
> +    public Book findOne(int id) {
getBookById

2023-01-12 19:40 UTC, sgaripovdigi requested changes
Внеси изменения

2023-01-30 09:06 UTC, niyazkadirov approved these changes

2023-01-30 09:06 UTC, niyazkadirov commented on src/main/java/com/example/petproject/entity/Book.java
> +    @Min(value = 0, message = "Year of publishing should be greater than 0")
Должно валидироватся в конроллере,т,е в слоц данных не должно проникать не валидные даннне

2023-01-30 09:06 UTC, niyazkadirov commented on src/main/java/com/example/petproject/entity/Book.java
> +    @Column(name = "updated_at")
colume -> updatable = false

2023-01-30 09:06 UTC, niyazkadirov commented on src/main/java/com/example/petproject/services/PeopleBaseService.java
> +        return person.get().getBooks();
npe

2023-01-31 18:11 UTC, merged